//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A.Resources.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("A.Resources.LanguageResources.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your language.
        /// </summary>
        internal static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose profession, service or city.
        /// </summary>
        internal static string ChooseProfServCity {
            get {
                return ResourceManager.GetString("ChooseProfServCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicked {0} times.
        /// </summary>
        internal static string Counter {
            get {
                return ResourceManager.GetString("Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English motherfucker.
        /// </summary>
        internal static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t ask again (Mode switching is still possible after logging in via Settings).
        /// </summary>
        internal static string LogInChooseView_DoNotAskMore {
            get {
                return ResourceManager.GetString("LogInChooseView_DoNotAskMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully logged in, continue as.
        /// </summary>
        internal static string LogInChooseView_KnownUserContinueAs {
            get {
                return ResourceManager.GetString("LogInChooseView_KnownUserContinueAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful registration, continue as.
        /// </summary>
        internal static string LogInChooseView_NewUserContinueAs {
            get {
                return ResourceManager.GetString("LogInChooseView_NewUserContinueAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as a self-employed / company.
        /// </summary>
        internal static string LogInChooseView_SignInAsCompanyShort {
            get {
                return ResourceManager.GetString("LogInChooseView_SignInAsCompanyShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as a user.
        /// </summary>
        internal static string LogInChooseView_SignInAsUserShort {
            get {
                return ResourceManager.GetString("LogInChooseView_SignInAsUserShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the application mode.
        /// </summary>
        internal static string LogInChooseView_Title {
            get {
                return ResourceManager.GetString("LogInChooseView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string LogInView_Close {
            get {
                return ResourceManager.GetString("LogInView_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        internal static string LogInView_DontHaveAccRegister {
            get {
                return ResourceManager.GetString("LogInView_DontHaveAccRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter e-mail or name.
        /// </summary>
        internal static string LogInView_EnterEMailOrAccName {
            get {
                return ResourceManager.GetString("LogInView_EnterEMailOrAccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        internal static string LogInView_EnterPassword {
            get {
                return ResourceManager.GetString("LogInView_EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        internal static string LogInView_ForgotPassword {
            get {
                return ResourceManager.GetString("LogInView_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in error.
        /// </summary>
        internal static string LogInView_LogInError {
            get {
                return ResourceManager.GetString("LogInView_LogInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook account.
        /// </summary>
        internal static string LogInView_LoginRegisterViaFacebook {
            get {
                return ResourceManager.GetString("LogInView_LoginRegisterViaFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google account.
        /// </summary>
        internal static string LogInView_LoginRegisterViaGoogle {
            get {
                return ResourceManager.GetString("LogInView_LoginRegisterViaGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to your account.
        /// </summary>
        internal static string LogInView_LogIntoAccount {
            get {
                return ResourceManager.GetString("LogInView_LogIntoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register here.
        /// </summary>
        internal static string LogInView_RegisterHere {
            get {
                return ResourceManager.GetString("LogInView_RegisterHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string LogInView_RememberLogIn {
            get {
                return ResourceManager.GetString("LogInView_RememberLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in as a self-employed / company.
        /// </summary>
        internal static string LogInView_SignInAsCompany {
            get {
                return ResourceManager.GetString("LogInView_SignInAsCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in as a user.
        /// </summary>
        internal static string LogInView_SignInAsUser {
            get {
                return ResourceManager.GetString("LogInView_SignInAsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in / register using.
        /// </summary>
        internal static string LogInView_SignInWithHelpOf {
            get {
                return ResourceManager.GetString("LogInView_SignInWithHelpOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the app.
        /// </summary>
        internal static string LogInView_WelcomeText {
            get {
                return ResourceManager.GetString("LogInView_WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string MenuSearchIconText {
            get {
                return ResourceManager.GetString("MenuSearchIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MenuSettingsIconText {
            get {
                return ResourceManager.GetString("MenuSettingsIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string PageSettingsTitle {
            get {
                return ResourceManager.GetString("PageSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterChooseView_RegisterAs {
            get {
                return ResourceManager.GetString("RegisterChooseView_RegisterAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as a self-employed / company.
        /// </summary>
        internal static string RegisterChooseView_RegisterAsCompanyShort {
            get {
                return ResourceManager.GetString("RegisterChooseView_RegisterAsCompanyShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as a user.
        /// </summary>
        internal static string RegisterChooseView_RegisterAsUserShort {
            get {
                return ResourceManager.GetString("RegisterChooseView_RegisterAsUserShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the registration method.
        /// </summary>
        internal static string RegisterChooseView_Title {
            get {
                return ResourceManager.GetString("RegisterChooseView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string RegisterCompanyView_Address {
            get {
                return ResourceManager.GetString("RegisterCompanyView_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image.
        /// </summary>
        internal static string RegisterCompanyView_ChooseImage {
            get {
                return ResourceManager.GetString("RegisterCompanyView_ChooseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company identification number.
        /// </summary>
        internal static string RegisterCompanyView_CIN {
            get {
                return ResourceManager.GetString("RegisterCompanyView_CIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string RegisterCompanyView_City {
            get {
                return ResourceManager.GetString("RegisterCompanyView_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of trade / company.
        /// </summary>
        internal static string RegisterCompanyView_CompanyName {
            get {
                return ResourceManager.GetString("RegisterCompanyView_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string RegisterCompanyView_EMail {
            get {
                return ResourceManager.GetString("RegisterCompanyView_EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo of Trade / Company.
        /// </summary>
        internal static string RegisterCompanyView_Image {
            get {
                return ResourceManager.GetString("RegisterCompanyView_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string RegisterCompanyView_NextView {
            get {
                return ResourceManager.GetString("RegisterCompanyView_NextView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string RegisterCompanyView_Phone {
            get {
                return ResourceManager.GetString("RegisterCompanyView_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code / ZIP code.
        /// </summary>
        internal static string RegisterCompanyView_PostalCode {
            get {
                return ResourceManager.GetString("RegisterCompanyView_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string RegisterCompanyView_RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterCompanyView_RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an translate text test.
        /// </summary>
        internal static string TranslateExt {
            get {
                return ResourceManager.GetString("TranslateExt", resourceCulture);
            }
        }
    }
}
